on:
  workflow_run:
    workflows: [Build Docker image]
    branches:
      - main
      - TECH-3253-update-maker-keeper-pipeline-to-use-IAM-role
    types:
      - completed

name: Deploy to AWS Production EKS

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: prod
    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: maker-prod

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.GA_OIDC_EKS_PROD }}
        role-session-name: MakerKeeper
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploying to EKS with Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.10
      with:
        cluster-name: ${{ env.CLUSTER_NAME }}
        config-files: deploy/prod/values.yaml
        chart-path: techops-services/common
        namespace: maker-keeper
        timeout: 5m0s
        name: maker-keeper
        chart-repository: https://techops-services.github.io/helm-charts
        version: 0.0.11
        atomic: true
