on:
  push:
    branches:
      - main
      - TECH-1350-fix-the-following-repos

name: Rebuild Docker image

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: '3.7.13'

    - name: run tests
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv --upgrade
        pip install $(cat requirements.txt $(find lib -name requirements.txt | sort) | sort | uniq | sed 's/ *== */==/g')
        pip install $(cat requirements-dev.txt $(find lib -name requirements-dev.txt | sort) | sort | uniq | sed 's/ *== */==/g')
        ./test.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to Dockerhub
      id: build-image
      run: |
        docker build -t makerdao/maker-keeper .
        docker push makerdao/maker-keeper